language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7rc3
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.6.3
script:
  - make test -v
notifications:
  email:
    on_success: change
    on_failure: always
services:
  - docker

