language: go
go:
  - 1.6.3
  - tip
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.6.3
    - secure: "XXIC4p9OVklr44HzE7zW5INInDN1N+WgCqrCEFwpN/Kk00unYdaV1LYabSENPEvR9UNS1ya1Bx+7M1hQAHXQnBVtrdYYdgkZvgj6QMFWWm4UTUIk+wqa1lsuXOEWAmsonAjx7XMITHyw9pDfNTwIEuU0XZIqzadAb5F6d4ES/pw9VcdhXJaNyIwRXLDSPDAa0mwnNJB9WBpKNiL5GTCkEHpp8O01eowzBuNGg/+b7WydjQpcu6KEez6IbvdoMQcnliPYdE+qpThV7LC1z3INgJs4HFB2JwKBZGYhc/6RwL7d3T06ZaRikBhX4B9KTi02RqbqacRcSJOcdyH+EoNbU9yW04C+WCF11mZn1fMLOnzR0kiadnyCagVBPe1mLiIYIfOM3bv2d5REa8zshbMIL2Y0Tx9k9P5KRNoiBfp3l8Ql1tlOuIPiVzDBMAvSLodxc6x9l2ySOaKL80ulc7Grr60y6jt5usaddjyqS4EIQsKQCxyUbraPzv1JiaN3CPYd5YXFVEIz0G7ERteXtzdB6AWMpIUIUp5ymYlxMWic3ei+2CTDoANCsNxmeZElMOY6v4/5BVgPwE0mbY2TaL9EpvJujB8KYe0t50OZ+ebChK50Q1jSfF8O+gU4rbesU1GnD0m5PKfEmFP5Gybqmz/XadgOQl2KCpLu3aHkdO3UTsQ="
    - secure: "fX6ZpYghS3DUcc/pNjwDNA4qwl8cQdfoYN9wnhEimymiU5NFtI9spQg/FlI9kMfQIW21QrhFvMFcMdXgEbdVnp98tcApxrCqU1kFU/LwhcC/r+7GOwwwreuTt6XLd8QMlVP9LhIgEqm0ic5grFnd8GfyEIhSSD8/4bXYHxE9ScSdspZntB3rbAJgfcjMqe9yNPrekkT9XC+F7dbnDmgdPuDwWLa0tvE6474d7bsoRtWtSTKETdZaCNa9LR53evgXpxOQ3qep6utBD9FbOSlj7W6P4jbzPBrTfpG04wl3LdhCob77GsBP2NUIhJK90OSsluBYHTUc6u08nQ0uJ/lKgPuKgR6PAutG+i9V+sY14cAEs9KIGOsLbp5ZZWg5/4OuCkZe8ULBxs+D1g4kVk+pJ1vqxLOd2AZG1t2HpQiJOYr/Jdmrs7R8L05bpA030tYiszcJ+g5MZkExPkOmbHONKbTNas+K4S5tzCDXe2ghtcCJ1sFozTrX5LEIU+652m9DM77pqesqmKW4jcCK3T2tJgdN8H2dVdtuGDG2D6/Rk8rb6Uw4wjxRjneipM5bSo3gQQ75oMwfVyWZzHP067CkIjd1ZRbs1moBXtQv8y9Y4QQLf2YA08Pc31RMCtXBlV/Dvp0yjvhRweok3ZkCwWL1Y3fKji4eAmuUuFkvkw/W5wk="
script:
  - make test
notifications:
  email:
    on_success: change
    on_failure: always
