# Site settings
title: "3nigm4"
email: jacob@jacobtomlinson.co.uk
description: "A command line chat based on keybase."
baseurl: "http://nexocrew.github.io/3nigm4/"
url: "http://nexocrew.github.io/3nigm4/"
title_description: "3nigm4 is a Go application developed by nexocrew. The purpose of the software is to provide a GPG-based framework, integrated with keybase as a trusted key server, offering secure chat and file sharing capabilities."
google_analytics: "UA-20365477-4"
disqus_account: http-nexocrew-github-io-3nigm4
github_repository: https://github.com/nexocrew/3nigm4
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  nexocrew

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://nexocrew.github.io/\">Nexocrew</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/nexocrew/3nigm4\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
